<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.example.org/Source/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Source"
	xmlns:undefined="http://www.example.org/source/undefined/"
	xmlns:qualified="http://www.example.org/source/qualified/"
	xmlns:unqualified="http://www.example.org/source/unqualified/"
	targetNamespace="http://www.example.org/Source/">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.example.org/source/undefined/">
			<xsd:element name="NewOperation">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="undefined" type="xsd:string" />
						<xsd:element name="qualified" type="xsd:string" form="qualified"/>
						<xsd:element name="unqualified" type="xsd:string" form="unqualified"/>
					</xsd:sequence>
					<xsd:attribute name="undefined" type="xsd:string" />
					<xsd:attribute name="qualified" type="xsd:string" form="qualified"/>
					<xsd:attribute name="unqualified" type="xsd:string" form="unqualified"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
		<xsd:schema targetNamespace="http://www.example.org/source/qualified/" elementFormDefault="qualified" attributeFormDefault="qualified">
			<xsd:element name="NewOperation">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="undefined" type="xsd:string" />
						<xsd:element name="qualified" type="xsd:string" form="qualified"/>
						<xsd:element name="unqualified" type="xsd:string" form="unqualified"/>
					</xsd:sequence>
					<xsd:attribute name="undefined" type="xsd:string" />
					<xsd:attribute name="qualified" type="xsd:string" form="qualified"/>
					<xsd:attribute name="unqualified" type="xsd:string" form="unqualified"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
		<xsd:schema targetNamespace="http://www.example.org/source/unqualified/" elementFormDefault="unqualified" attributeFormDefault="unqualified">
			<xsd:element name="NewOperation">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="undefined" type="xsd:string" />
						<xsd:element name="qualified" type="xsd:string" form="qualified"/>
						<xsd:element name="unqualified" type="xsd:string" form="unqualified"/>
					</xsd:sequence>
					<xsd:attribute name="undefined" type="xsd:string" />
					<xsd:attribute name="qualified" type="xsd:string" form="qualified"/>
					<xsd:attribute name="unqualified" type="xsd:string" form="unqualified"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
</wsdl:definitions>
